namespace AnimeTracker.Api.Models;

/// <summary>Singleton bookkeeping row (one ever): a GUID generated by the app
/// on this database's first start, and never configured or rewritten
/// afterwards (see <c>Services/Transfer/DeviceIdentityInitializer</c>). It
/// identifies this database's installation in export headers, distinct from
/// any anime or user data.</summary>
public class DeviceIdentity
{
    public int Id { get; set; }
    public Guid DeviceId { get; set; }
}
