// <auto-generated />
using System;
using AnimeTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimeTracker.Api.Migrations
{
    [DbContext(typeof(AnimeTrackerDbContext))]
    [Migration("20260707213251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimeTracker.Api.Models.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeDetail")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("Timestamp");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeMetadata", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("AiredFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AiredTo")
                        .HasColumnType("date");

                    b.Property<string>("AiringStatus")
                        .HasColumnType("text");

                    b.Property<string>("BroadcastDayOfWeek")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("BroadcastTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset?>("LastScoreSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MalScore")
                        .HasColumnType("double precision");

                    b.Property<string>("MediaType")
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<int?>("PopularityRank")
                        .HasColumnType("integer");

                    b.Property<string>("Studio")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AnimeMetadata");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.UserAnimeEntry", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date");

                    b.Property<int>("EpisodesWatched")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MyScore")
                        .HasColumnType("integer");

                    b.Property<bool>("PendingSync")
                        .HasColumnType("boolean");

                    b.Property<int>("RewatchCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartedAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnimeId");

                    b.ToTable("UserAnimeEntries");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.UserAnimeEntry", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithOne("UserEntry")
                        .HasForeignKey("AnimeTracker.Api.Models.UserAnimeEntry", "AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeMetadata", b =>
                {
                    b.Navigation("UserEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
