// <auto-generated />
using System;
using System.Collections.Generic;
using AnimeTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimeTracker.Api.Migrations
{
    [DbContext(typeof(AnimeTrackerDbContext))]
    [Migration("20260906192011_StoreArtworkChoicesWithTimestamps")]
    partial class StoreArtworkChoicesWithTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimeTracker.Api.Models.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeDetail")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PreviousEpisodesWatched")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("BetterMal");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("Timestamp");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AiringRefreshState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("BackfillCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPassSeason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSuccessfulPassAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AiringRefreshStates");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AniListRelation", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedAnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("RelationType")
                        .HasColumnType("text");

                    b.HasKey("AnimeId", "RelatedAnimeId", "RelationType");

                    b.HasIndex("AnimeId");

                    b.HasIndex("RelatedAnimeId");

                    b.ToTable("AniListRelations");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeAiringSync", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("AniListId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCompleteData")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAiringEpisodeAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextRecheckAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RelationsFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AnimeId");

                    b.ToTable("AnimeAiringSyncs");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeMetadata", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("AiredFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AiredTo")
                        .HasColumnType("date");

                    b.Property<string>("AiringStatus")
                        .HasColumnType("text");

                    b.Property<int?>("AniListTotalEpisodes")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageEpisodeDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<string>("BroadcastDayOfWeek")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("BroadcastTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("EnglishTitle")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("LastScoreSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MalPictureUrl")
                        .HasColumnType("text");

                    b.Property<double?>("MalScore")
                        .HasColumnType("double precision");

                    b.Property<int?>("MalTotalEpisodes")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PictureUrls")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("PicturesSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PopularityRank")
                        .HasColumnType("integer");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Rating")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SelectedPictureModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectedPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Studio")
                        .HasColumnType("text");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AnimeMetadata");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeRelatedAnime", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedAnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("RelationType")
                        .HasColumnType("text");

                    b.Property<string>("MediaType")
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnimeId", "RelatedAnimeId", "RelationType");

                    b.HasIndex("AnimeId");

                    b.HasIndex("RelatedAnimeId");

                    b.ToTable("AnimeRelatedAnime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kinds")
                        .HasColumnType("integer");

                    b.Property<int?>("MovedEpisode")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("NewEpisodeDate")
                        .HasColumnType("date");

                    b.Property<string>("PreviousBroadcastDayOfWeek")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("PreviousBroadcastTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly?>("PreviousEpisodeDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PreviousStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("DetectedAt");

                    b.ToTable("AnimeUpdates");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.EpisodeAiring", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("Episode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AirsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AnimeId", "Episode");

                    b.HasIndex("AnimeId", "AirsAtUtc");

                    b.ToTable("EpisodeAirings");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.PendingEntryDeletion", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("HeldForReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AnimeId");

                    b.ToTable("PendingEntryDeletions");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.PendingReconciliationDiff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PendingReconciliationDiffs");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.PendingReconciliationDiffEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date");

                    b.Property<int>("EpisodesWatched")
                        .HasColumnType("integer");

                    b.Property<int?>("MyScore")
                        .HasColumnType("integer");

                    b.Property<int>("PendingReconciliationDiffId")
                        .HasColumnType("integer");

                    b.Property<int>("RewatchCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartedAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PendingReconciliationDiffId");

                    b.ToTable("PendingReconciliationDiffEntries");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.ReconciliationRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ReconciliationRunLogs");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.RelationDiscovery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RelatedAnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("DiscoveredAt");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("RelationDiscoveries");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.SeasonAnimeListing", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.HasKey("Year", "Season", "AnimeId");

                    b.HasIndex("AnimeId");

                    b.ToTable("SeasonAnimeListings");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.SeasonFetchLog", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Year", "Season");

                    b.ToTable("SeasonFetchLogs");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BuiltAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTruncated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("SelectedPictureModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectedPictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SelectedTitle")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SelectedTitleModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.SeriesMember", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("BranchHeadAnimeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMainLine")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MembershipKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Core");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("RelationGroup")
                        .HasColumnType("text");

                    b.Property<int?>("VersionSlotKey")
                        .HasColumnType("integer");

                    b.HasKey("SeriesId", "AnimeId");

                    b.HasIndex("AnimeId");

                    b.HasIndex("SeriesId");

                    b.ToTable("SeriesMembers");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.TopAnimeFetchLog", b =>
                {
                    b.Property<string>("RankingType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RankingType");

                    b.ToTable("TopAnimeFetchLogs");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.TopAnimeRankingEntry", b =>
                {
                    b.Property<string>("RankingType")
                        .HasColumnType("text");

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("RankingType", "AnimeId");

                    b.HasIndex("AnimeId");

                    b.ToTable("TopAnimeRankingEntries");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.TopAnimeSelection", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AnimeId");

                    b.ToTable("TopAnimeSelections");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.UserAnimeEntry", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date");

                    b.Property<int>("EpisodesWatched")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("HeldForReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MyScore")
                        .HasColumnType("integer");

                    b.Property<bool>("PendingSync")
                        .HasColumnType("boolean");

                    b.Property<int>("RewatchCount")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly?>("StartedAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnimeId");

                    b.ToTable("UserAnimeEntries");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AniListRelation", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeAiringSync", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeRelatedAnime", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany("RelatedAnime")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeUpdate", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.EpisodeAiring", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", null)
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.PendingEntryDeletion", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.PendingReconciliationDiffEntry", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.PendingReconciliationDiff", "Diff")
                        .WithMany("Entries")
                        .HasForeignKey("PendingReconciliationDiffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diff");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.RelationDiscovery", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.SeasonAnimeListing", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.SeriesMember", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeTracker.Api.Models.Series", null)
                        .WithMany("Members")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.TopAnimeRankingEntry", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.TopAnimeSelection", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.UserAnimeEntry", b =>
                {
                    b.HasOne("AnimeTracker.Api.Models.AnimeMetadata", "Anime")
                        .WithOne("UserEntry")
                        .HasForeignKey("AnimeTracker.Api.Models.UserAnimeEntry", "AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.AnimeMetadata", b =>
                {
                    b.Navigation("RelatedAnime");

                    b.Navigation("UserEntry");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.PendingReconciliationDiff", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AnimeTracker.Api.Models.Series", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
